# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudectx < Formula
  desc "Fast, safe profile switching for Claude Code"
  homepage "https://github.com/foxj77/claudectx"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/foxj77/claudectx/releases/download/v1.0.0/claudectx_1.0.0_darwin_amd64.tar.gz"
      sha256 "4a2d414b149e71e1ddeef7734dabff3e12972b30ec805d499ecd3b12960e8e31"

      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
    on_arm do
      url "https://github.com/foxj77/claudectx/releases/download/v1.0.0/claudectx_1.0.0_darwin_arm64.tar.gz"
      sha256 "4ec5892062b66e3e1ea52a460a3deabc3dcd0f89454b1287cc86de17ebc85cec"

      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foxj77/claudectx/releases/download/v1.0.0/claudectx_1.0.0_linux_amd64.tar.gz"
        sha256 "35aeef62531fc6c23d691d38e123e70856cd183d4c5dc1c6422bc407f74d839d"

        def install
          bin.install "claudectx"

          # Install shell completions
          bash_completion.install "completion/bash_completion.sh" => "claudectx"
          zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
          fish_completion.install "completion/fish_completion.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foxj77/claudectx/releases/download/v1.0.0/claudectx_1.0.0_linux_arm64.tar.gz"
        sha256 "c8a0da1386c63271326e9d17a6d06ba455766785407a04f256d70f00c0182c96"

        def install
          bin.install "claudectx"

          # Install shell completions
          bash_completion.install "completion/bash_completion.sh" => "claudectx"
          zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
          fish_completion.install "completion/fish_completion.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/claudectx", "--version"
  end
end
