# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudectx < Formula
  desc "Fast, safe profile switching for Claude Code"
  homepage "https://github.com/foxj77/claudectx"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foxj77/claudectx/releases/download/v1.1.1/claudectx_1.1.1_darwin_amd64.tar.gz"
      sha256 "d315b29c74b83d9e739b8124dd69f1a0a8e0c55b53ef4c0f236eee2cd893e7ea"

      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foxj77/claudectx/releases/download/v1.1.1/claudectx_1.1.1_darwin_arm64.tar.gz"
      sha256 "fd35a76012f97df94c79b4e7646c2d550880c8a003b151646e33730d287b79d2"

      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxj77/claudectx/releases/download/v1.1.1/claudectx_1.1.1_linux_amd64.tar.gz"
      sha256 "a45637c6ae67f49e384a0c82b0bb29d80fd7bc2424e72da060000ebe3660f6ed"
      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxj77/claudectx/releases/download/v1.1.1/claudectx_1.1.1_linux_arm64.tar.gz"
      sha256 "ada80693246074e9f38d069a1902b80c4b3647d931be623c653b636fbb6402cf"
      def install
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
  end

  test do
    system "#{bin}/claudectx", "--version"
  end
end
