# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudectx < Formula
  desc "Fast, safe profile switching for Claude Code"
  homepage "https://github.com/foxj77/claudectx"
  version "1.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foxj77/claudectx/releases/download/v1.2.4/claudectx_1.2.4_darwin_amd64.tar.gz"
      sha256 "361142f067027b3a98ef644c9ff972e5f059285fbef2a592fde10b1ddac3744a"

      define_method(:install) do
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foxj77/claudectx/releases/download/v1.2.4/claudectx_1.2.4_darwin_arm64.tar.gz"
      sha256 "acb1659b95d742dd06973efb09efea8458996f8a4c51c52642fce41e0478e6d2"

      define_method(:install) do
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxj77/claudectx/releases/download/v1.2.4/claudectx_1.2.4_linux_amd64.tar.gz"
      sha256 "0cb3f8c098b24422217659a70b0acacac3f56c4cdbcbc1939b9a098149ce0233"
      define_method(:install) do
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foxj77/claudectx/releases/download/v1.2.4/claudectx_1.2.4_linux_arm64.tar.gz"
      sha256 "5c6631f7a2401e57a24234d1468ccfcb4ef4bc1ff9f3531669751ea91bbffb56"
      define_method(:install) do
        bin.install "claudectx"

        # Install shell completions
        bash_completion.install "completion/bash_completion.sh" => "claudectx"
        zsh_completion.install "completion/zsh_completion.sh" => "_claudectx"
        fish_completion.install "completion/fish_completion.fish"
      end
    end
  end

  test do
    system "#{bin}/claudectx", "--version"
  end
end
